AllCops:
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Naming/PredicatePrefix:
  Exclude:
    - "lib/quail/resource/dsl.rb"

Style/ArgumentsForwarding:
  Exclude:
    - "lib/quail/resource/dsl.rb"

Style/ParallelAssignment:
  Enabled: false

Style/Documentation:
  Exclude:
    - "test/**/*"

Metrics:
  Exclude:
    - "test/**/*"

Naming/FileName:
  Exclude:
    - 'lib/quail-graphql.rb'
